name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run tests
        run: uv run pytest

      - name: Upload Coverage Results
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./lcov.info

      - name: Build package
        run: |
          uv build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{github.ref_name}}
          files: dist/*
          generate_release_notes: true

      - name: Publish package to PyPI
        run: |
          uv publish
